[package]
name = "jello-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[workspace]

[dependencies]
libfuzzer-sys = "0.4"
jello = { path = ".." }

[[bin]]
name = "repair"
path = "fuzz_targets/repair.rs"
test = false
doc = false
bench = false

[[bin]]
name = "diff"
path = "fuzz_targets/diff.rs"
test = false
doc = false
bench = false
